### ISSUE TITLE
Network location issues with microg/unifiedNlp [lineage-17.1]

### ISSUE THREAD

**Issue by tempte** [BYZYB/android_device_xiaomi_libra#14]
It seems that network location locks just once the phone is started (or backend is turned off/on), no location refresh then. Backend location permission is granted (Allowed all the time). GPS works as expected and not an issue.
Is it known for Lineage (or this specific ROM) like possible incompatibility with com.qualcomm.location? Any solutions?

microG Services Core 0.2.13.203915
Mozilla UnifiedNlp Backend 1.4.0.20033

**Comment by BYZYB** [comment]
> It seems that network location locks just once the phone is started (or backend is turned off/on), no location refresh then. Backend location permission is granted (Allowed all the time). GPS works as expected and not an issue.
> Is it known for Lineage (or this specific ROM) like possible incompatibility with com.qualcomm.location? Any solutions?
> 
> microG Services Core 0.2.13.203915
> Mozilla UnifiedNlp Backend 1.4.0.20033

When I was using MicroG on my device at past, the same issue happened. I think it was caused by background app limitation (see "Battery optimization" in Settings), but not "com.qualcomm.location". Did you add MicroG and location backend apps into "battery optimization whitelist"?

If the location provider is limited to run background, it would update location (or restore from a freeze state, just like other apps outside the whitelist) only when some broadcasts are triggered. When the device started, no app would be freeze in the first few minutes, then some background activities might be limited. I don't like to add any apps into whitelist (but set background limit for all apps in my device), so I never had a test about this issue.

For GPS, which is a hardware feature but not something controlled by apps, should not be affected by background app limits.

**Comment by tempte** [comment]
Thank you for the hint. Initially missed the absence of Nlp Backend in Standby apps (Dev. options) where microG itself is "Exempted" (actually there is limited list of apps present). Found Backend in Settings - Apps & Notifications - Special app access - Battery optimization, switched to "Don`t optimize". Will test the settings.
