### ISSUE TITLE
Pure Black in Dark Theme is broken in Lineage 17.1 20210615 build

### ISSUE THREAD

**Issue by dibyanugraha** [BYZYB/android_device_xiaomi_libra#20]
Pure black in dark theme is broken in Lineage 17.1 20210615 build. It used to work in Lineage 17.1 20210512

**Comment by BYZYB** [comment]
Extra theme support (exactly, `LineageBlackTheme` and all overlay packages in `/system/product/overlays`) has been removed to reduce resource consumption and improve performance. That's why gesture navigation, icon shapes and the pure black theme you mentioned is not supported currently. Mi-4c doesn't have an OLED screen, so using black theme will not save power. If you really like this feature, ~~I could build the packages manually and send them to you~~ (I just remember I have deleted the sources of lineage-17.1 on my computer) you could find `LineageBlackTheme` in previous builds and copy it to the same directory.

**Comment by dibyanugraha** [comment]
I see, thank you for the solid explanation.
