### ISSUE TITLE
Need to alter partition sizes for Gapps?

### ISSUE THREAD

**Issue by zawsx** [BYZYB/android_device_xiaomi_libra#24]
Hi! Thanks for this excellent work and for your expertise and commitment - you've saved tonnes of carbon by extending phone life.
I've got it running well on my Mi4c but can't install gapps: neither pico nor full.
I've installed your TWRP [https://github.com/BYZYB/android_device_xiaomi_libra/releases/download/v2021.11.13/TWRP-20211222-3.3.1.0-libra.img](https://github.com/BYZYB/android_device_xiaomi_libra/releases/download/v2021.11.13/TWRP-20211222-3.3.1.0-libra.img)
Then did an adb sideload of the Arm64 Android 11 Gapps from [opengapps](https://opengapps.org/)
After about 5% TWRP reports an error 70 - not enough space on the partition.
 
Are  'super' partitions a way forward as Android 11 supports them? [https://source.android.com/devices/tech/ota/dynamic_partitions](https://source.android.com/devices/tech/ota/dynamic_partitions)
or should I try myself to resize the existing partitions? This tool seems old but might work? [https://github.com/Lanchon/REPIT](https://github.com/Lanchon/REPIT) 

Any advice gratefully received as I guess this is an issue for everyone wanting to use Gapps.
Thanks again for helping save the planet :)

**Comment by BYZYB** [comment]
Dynamic partitions is only available on new devices (mainly on Pixel phones), as the bootloader is also required to support new partition types (not only Android itself). However, resizing the partition is a possible solution, and I also heard some users have resized the partitions successfully (remember to backup the data first).

There are also some safe solutions rather than altering the partition table. For example, deleting the NotoSansCJK fonts will save 100MB+ space if Chinese/Japanese/Korean is not your main language (also documented at [my XDA post](https://forum.xda-developers.com/t/rom-8-1-9-10-11-unofficial-lineageos-for-mi-4c-mi-4s.4008625/post-80995719)).

If that's not enough, deleting the prebuilt "webview" package and install a new one will save another 100MB+ space. You could boot into the system and install Google Webview (download the APK in your preferred ways), then delete the prebuilt one from `system/product/app` and reboot (only delete it after installation).

**Comment by zawsx** [comment]
Thanks! Hope, as always, in helping me you help others seeing this.

Had deleted the fonts but even pico gapps failed due to insufficient storage. 
Looked at replacing Webview but it seemed beyond me, too complex and I couldn't find the original webview on the phone.
Found a step by step on resizing the partitions as there is 372Mb cache that cold be shrunk to allow the system partition to grow large enough

adb push parted /
adb push gdisk /
adb shell
umount /cache
chmod +x parted
chmod +x gdisk
parted /dev/block/mmcblk0p42
resizepart 372 300M

The final step doesn't work for me, 
parted shows the cache partition as a 403Mb 'loop' partition - meaning it's a file within a file.

BTW I noticed TWRP errors sideloading: '**Could not mount  /data and unable to find crypto footer**'
Chris.

**Comment by BYZYB** [comment]
> Found a step by step on resizing the partitions as there is 372Mb cache that cold be shrunk to allow the system partition to grow large enough

This XDA post may help you: [post-85742177](https://forum.xda-developers.com/t/rom-8-1-9-10-11-unofficial-lineageos-for-mi-4c-mi-4s.4008625/post-85742177)

> Looked at replacing Webview but it seemed beyond me, too complex and I couldn't find the original webview on the phone.

The webview package could be replaced using these adb/shell commands:

1. Download the Google Webview package from [APKMirror](https://www.apkmirror.com/apk/google-inc/android-system-webview/android-system-webview-97-0-4692-98-release/android-system-webview-97-0-4692-98-3-android-apk-download/).
2. Install the APK file with `adb install xxx.apk`, or just install it with any file manager.
3. Run shell commands: `mount / -o remount,rw && rm -rf /system/product/app/webview/`.
4. Reboot the device and check the current webview at `Settings > System > Developer options` (Google Webivew should be selected).

> BTW I noticed TWRP errors sideloading: '**Could not mount /data and unable to find crypto footer**' Chris.

As "/data" is not encrypted by default, it's not needed to decrypt the partition in recovery.
