### ISSUE TITLE
Wrong battery level when charging [lineage-17.1 | QC-2.0 only]

### ISSUE THREAD

**Issue by Hikari31768** [BYZYB/android_device_xiaomi_libra#3]
Sometimes I charge my libra, the battery level up to about 30%-40% then stuck. But it can continue to charge to around 4.3v. When I replug the power line in. It charge in a very high speed with
 a tiny current.

![微信图片_20200421223922](https://user-images.githubusercontent.com/60568280/79880001-01ab9d00-8422-11ea-9738-b89de2db58c4.png)
![微信图片_20200421223937](https://user-images.githubusercontent.com/60568280/79880007-053f2400-8422-11ea-8aae-71fce01ff44b.png)（this is after I replug the power line)

**Comment by BYZYB** [comment]
> Sometimes I charge my libra, the battery level up to about 30%-40% then stuck. But it can continue to charge to around 4.3v. When I replug the power line in. It charge in a very high speed with
> a tiny current.
> 
> ![微信图片_20200421223922](https://user-images.githubusercontent.com/60568280/79880001-01ab9d00-8422-11ea-9738-b89de2db58c4.png)
> ![微信图片_20200421223937](https://user-images.githubusercontent.com/60568280/79880007-053f2400-8422-11ea-8aae-71fce01ff44b.png)（this is after I replug the power line)

**This is a duplicate issue to #1.**
Sorry for the short (too simple) description in that issue (and this one has been mentioned in #1).

I have noticed this problem since the first version of lineage-17.1, which should be something wrong in the rom but not kernel. When charging with original charger (using QC-2.0), the charging speed seems too slow but the battery **has been charged** (that's why you found the charging speed became too high in some situation).
Currently, the most easy way to charge the device is connecting to USB port that doesn't support quick charge (eg. your PC, some power banks). This issue **should be avoided** in that way, and the charging speed is **only a little slower** than QC-2.0 (benefits from this [patch](https://github.com/WJXXBSH/android_kernel_xiaomi_libra/commit/4136fabbe9028ed89192add9bde63fa8ab7c6984)). When you see "正在慢速充电" on your lockscreen, it should be right.
At first, I think this problem should be a "Mi-4c specific issue", then I could try to find some solutions from similar device like Nexus 5x or Oneplus 2. However, the same problem happened to Nexus 5x (including the volume issue), so it could not be fixed in a short time.
