### ISSUE TITLE
Max volume increasing [kernel]

### ISSUE THREAD

**Issue by haydar** [BYZYB/android_device_xiaomi_libra#4]
Speaker power of Mi 4c is not enough to listen something on the open area. I am using a volume booster app because of this. Can you increase the max volume by at least  %10 with rom?

**Comment by BYZYB** [comment]
> Speaker power of Mi 4c is not enough to listen something on the open area. I am using a volume booster app because of this. Can you increase the max volume by at least %10 with rom?

Increase the max volume is possible, but I'm not sure if it will be harm (permanently) for the speaker. Unlike CPU/GPU overclock (which will result in random reboot or heating), it could damage the hardware if keeps playing sound in a higher volume than stock value.

**Comment by haydar** [comment]
I already use volume increased by 10% last 2 months. it didn't happen any damage.

**Comment by BYZYB** [comment]
> I already use volume increased by 10% last 2 months. it didn't happen any damage.

Could you tell me which sound control app are you using?
Also, would you like to use faux sound control driver (built into the kernel) to set speaker gains, instead of modify the stock value for others? The control point is in "/system/kernel/sound_control_3", the gain of speaker/headphone/mic could be set by shell commands (or a script).

**Comment by haydar** [comment]
I don't want you effort just for me. I handled it. Thanks to your reply.
