### ISSUE TITLE
Android debugging turns on each boot [lineage-16.0 | lineage-17.1]

### ISSUE THREAD

**Issue by tempte** [BYZYB/android_device_xiaomi_libra#7]
Once activated "Android debugging" (Developer settings > Debugging) turns on again every boot even if it was off before reboot. 

Seems to be the same issue:
https://gitlab.com/LineageOS/issues/android/issues/308
https://review.lineageos.org/c/LineageOS/android_device_xiaomi_sdm845-common/+/253967

**Comment by BYZYB** [comment]
> Once activated "Android debugging" (Developer settings > Debugging) turns on again every boot even if it was off before reboot.
> 
> Seems to be the same issue:
> https://gitlab.com/LineageOS/issues/android/issues/308
> https://review.lineageos.org/c/LineageOS/android_device_xiaomi_sdm845-common/+/253967

This is a known issue since lineage-15.1 (even if it used different device/kernel/vendor from 16.0/17.1). I have searched for suspected properties in this repository, but got nothing valuable at last.
In my previous test, USB debugging is enabled just after boot completed (you could connect your device to computer, to see exactly when it will be enabled). However, the commands that executed after boot completed (on property:sys.boot_completed=1) are also not related to USB modes.

**Comment by BYZYB** [comment]
Right, after checking the logics of `init.qcom.usb.sh` and `init.qcom.usb.rc`, I think the reason of this issue has been found. By removing the wrong things from the scripts, ADB never enables after boot if it's disabled previously. See commit: 3fa9538.
Although the patch you provided is not suitable for libra, it still inspired me about the way to fix this issue. This issue will be resolved in the next rom update, you could also replace changed files by yourself to fix it instantly. Thanks for your feedback.
