### ISSUE TITLE
Carrier aggregation (4G+/LTE-A) support [lineage-16.0 | lineage-17.1]

### ISSUE THREAD

**Issue by tempte** [BYZYB/android_device_xiaomi_libra#9]
While the question may be not directly related to ROM as QPST, QXDM flash tools are involved - is it possible for this phone?  The processor should support up to 3xCA "3x20 MHz carrier aggregation" as stated Qualcomm specifications and in theory may greatly increase data transfer speed subject to local cellular networks and allowed modes.

Did not get a right guide, so as a reference used the below (not for libra, not for custom rom).
https://forum.xda-developers.com/mi-a1/how-to/guide-enable-4g-lte-carrier-aggregation-t3894282

In my case QPST does not recognize connected phone in proper way (while it is listed in Windows Device manager > COM & LPT ports) that may be an issue with drivers, OS, or other incompatibility. So cannot confirm if manual selection of bands to aggregate works. 

Is there any alternative/confirmed way to turn on Carrier aggregation, maybe incl. built in but hidden options?

Thanks for keeping the old phone alive!

**Comment by BYZYB** [comment]
Sadly, although the soc msm8992 support 4G+, but the antenna (signal line) inside Mi-4c doesn't support it at all. So Mi-4c doesn't support carrier aggregation because of **hardware limitations**.
There are also some users who have asked Xiaomi customer service about this question, and the answers are the same: only Mi-Note-Pro support 4G+.
